#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# Фокус при наведении курсора, а не нажатии
bspc config focus_follows_pointer true
bspc config pointer_modifier super

# Если окно одно, то в режим монокля
#bspc config single_monocle true


xsetroot -cursor_name left_ptr & 
picom &
polybar & 
nitrogen --restore &
numlockx &



# Правила для окон
bspc rule -a discord desktop=3 
bspc rule -a TelegramDesktop desktop=3
bspc rule -a Chromium desktop=2 
bspc rule -a steam desktop=1  follow=on
bspc rule -a scrcpy state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a yad-calendar border=off

